openapi:3.0.0
info:
  title: Sample API
  description: A sample API to demonstrate OpenAPI 3.0 specification
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Main production server
  - url: https://staging-api.example.com/v1
    description: Staging server
paths:
  /items:
    post:
      summary: Create a new item
      requestBody:
        required: true
        content:
          application/id+json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: The unique identifier for the item
                name:
                  type: string
                  description: The name of the item
              required:
                - id
                - name
      responses:
        '201':
          description: Item created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
